name: STJ Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  NODE_OPTIONS: --max-old-space-size=4096
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --legacy-peer-deps
#        working-directory: ./website
      - run: npm run build --if-present
#        working-directory: ./website
      - run: npm run test --if-present
#        working-directory: ./website
